
   export const ELECTRONICS_LOADING= 'ELECTRONICS_LOADING';
   export const ELECTRONICS_SUCCESS= 'ELECTRONICS_SUCCESS';
   export const ELECTRONICS_ERROR= 'ELECTRONICS_ERROR';
   export const ADD_TO_CART = 'ADD_TO_CART';
   export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
   export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
   export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';